theme = "material_darker"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
"'" = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"
'"' = ":sh zellij run -c -f -x 10% -y 10% --width 80% --height 80% -- lazygit"
r = "replace_with_yanked"
R = "replace"
'}' = "goto_next_paragraph"
'{' = "goto_prev_paragraph"

[keys.normal.g]
s = "goto_line_start"
h = "goto_first_nonwhitespace"

[keys.normal.m]
w = "@miw"
W = "@miW"
p = "@mip"
t = "@mit"
f = "@mif"
a = "@mia"
c = "@mic"
T = "@miT"
e = "@mie"
g = "@mig"
"(" = "@mi("
")" = "@mi)"
"{" = "@mi{"
"}" = "@mi}"
"[" = "@mi["
"]" = "@mi]"
"'" = "@mi'"
'"' = '@mi"'

[editor]
scrolloff = 8
bufferline = "always"
color-modes = true
jump-label-alphabet = "aeiounrtsgbldwjzxmcv"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
character = "|"
