theme = "material_darker"

[editor.cursor-shape]
insert = "bar"

[keys.normal."backspace"]
e = ":sh zellij run --close-on-exit --floating -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh open"
g = ":sh zellij run --close-on-exit --floating -x 10% -y 10% --width 80% --height 80% -- lazygit"

[keys.normal]
r = "replace_with_yanked"
R = "replace"
'}' = "goto_next_paragraph"
'{' = "goto_prev_paragraph"
'-' = "decrement"
'=' = "increment"
"'" = ":format"
H = "extend_to_first_nonwhitespace"
L = "extend_to_line_end"

[keys.select]
H = "extend_to_line_start"
L = "extend_to_line_end"

[keys.normal.g]
s = "goto_line_start"
h = "goto_first_nonwhitespace"

[keys.normal.m]
w = "@miw"
W = "@miW"
p = "@map"
t = "@mit"
f = "@mif"
c = "@mic"
T = "@miT"
e = "@mie"
g = "@mig"
"(" = "@mi("
")" = "@mi)"
"{" = "@mi{"
"}" = "@mi}"
"[" = "@mi["
"]" = "@mi]"
"'" = "@mi'"
'"' = '@mi"'

[editor]
true-color = true
scrolloff = 8
bufferline = "always"
color-modes = true
jump-label-alphabet = "aeiounrtsgbldwjzxmcv"
rulers = [80]
auto-pairs = false

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
character = "|"
